### PR TITLE
Add rpm packaging

### PR DESCRIPTION
**Pull request by ZpmFred**

### CODE REVIEW

**Comment by dswd** [comment]
Hello, thank you very much for this contribution. Will the package also work for other RPM based distributions like Fedora, SuSe, RHEL and Mandriva?

Also I am in the progress of creating a build chain for packages based on docker and host repositories containing the results. Could you point me to a howto on hosting RPM repositories?

**Comment by dswd** [comment]
I just tried to build an RPM package using your instructions but failed:

$> cargo rpm build --release
/home/user/.cargo/bin/cargo-rpm: unrecognized option `--release`

Even without --release:

$> cargo rpm build
error: No [package.metadata.rpm] in Cargo.toml!

Run 'cargo rpm init' to configure crate for RPM builds

**Comment by ZpmFred** [comment]
How sorry it seems like i forgot to push the Cargo.toml. I currently do not have access to the computer with the sources but if you do 'cargo rpm init' it will fill the Cargo.toml, then just replace the .rpm/vpncloud.spec with mine and then 'cargo rpm build' should work (I confirm the '--release' is an error of my part).

As for the compatibility with others RPM based distributions I do not known, I am pretty new to those kind of distribution (2 week) so I am sorry but I don't have the knowledge to help you.

I just needed to have an easy way of installing vpncloud on CentOS 7 and thought I will share with you.

**Comment by dswd** [comment]
Ok, I fixed the build process accordingly. Thanks for your contribution.

**Pull request merged**
